### ISSUE TITLE
Position reached information

### ISSUE THREAD

**Issue by bremenpl** [teknoman117/beaglebot#6]
Hello there,
I am build an application using BeagleBone Black where I need to read the position from 2 encoders on 2 motors. I have 2 question regarding your api:
- One of my encoder gives back quadrature signal only on 1 pin, not 2. I have seen in the MCU datasheet that there is a mode in eQEP that allows this. Can it be also configured using your API?
- Is there a way to get an interrupt in userspace application that position has been reached, or I need to check the counter in a loop?

I would aprichiate any help.

**Comment by teknoman117** [comment]
The driver does support encoders with only one count pin.  See https://github.com/Teknoman117/beaglebot/tree/master/encoders/dts#eqep-driver-configuration for information about the configuration options.  Check out "count_mode."

The driver currently does not support interrupt on compare match as of yet.  This is planned for the next version of the driver.  I hope to finish it sometime around mid January.

**Comment by bremenpl** [comment]
Thanks you for the answer. The deadline for my project occurs sooner than 
the time you are planing to implement interrups, so i will have to work it 
out somehow :/. I have enwountered a big problem in general when entering 
bbb programing that I cannot use any interrupts and everything has to be 
poolled... I dont even know either I can have an interrupt on RX complete 
in uart peripheral. This is very flustrating that something that is easily 
done in a bare metal programming mcu seems so complicated here.
If its not to much, would you mind a short explanation of how interrupts 
should be handled in general? Ive read somewhere that modules are abble to 
have them, but not userspace applications. Maybe I could implement motor 
sstopping on compare match in a module? I would aprichiate any help really.

Dnia 29 listopada 2014 04:21:09 Nathaniel Lewis notifications@github.com 
napisał(a):
